name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy Backend
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and deploy the backend
        run: |
          cd actions-runner-node
          cp -r $GITHUB_WORKSPACE/. .
          docker-compose up -d backend  # Start backend independently
